spring:
  application:
    name: backend

ai.versum:
  ollama:
    enabled: false
    baseUrl: http://localhost:11434
  openai:
    enabled: true
    apiKey: sk_test_1234567890

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
    expiration-time: 3600000