spring:
  application:
    name: backend

ai.versum:
  ollama:
    enabled: true
    baseUrl: http://localhost:11434
  openai:
    enabled: false
    apiKey: sk_test_1234567890
  vertexai:
    enabled: false
    apiKey: api_test_1234
    projectName: test_project
    location: europe-central2
